version: '3'
services:
  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"
  db: 
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=david
      - POSTGRES_DB=db

  pgadmin:
    container_name: 'pgadmin'
    image: dpage/pgadmin4
    ports:
      - '80:80'
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: david@example.com
      PGADMIN_DEFAULT_PASSWORD: password
